app = "bot-global-chat"
primary_region = "nrt"
[build]
[processes]
  app = "node dist/bot.cjs"
[env]
  NODE_ENV = "production"
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "256mb"
  processes = ["app"]
